#ifndef ALE_DO_TESTS_TEST_ALE_RECALC_MQH_INCLUDED
#define ALE_DO_TESTS_TEST_ALE_RECALC_MQH_INCLUDED

bool Test_ALE_Recalc_Run()
  {
   return(true);
  }

#endif // ALE_DO_TESTS_TEST_ALE_RECALC_MQH_INCLUDED
