#ifndef ALE_DO_TESTS_TEST_FSM_RESTORE_MQH_INCLUDED
#define ALE_DO_TESTS_TEST_FSM_RESTORE_MQH_INCLUDED

bool Test_FSM_Restore_Run()
  {
   return(true);
  }

#endif // ALE_DO_TESTS_TEST_FSM_RESTORE_MQH_INCLUDED
