#ifndef ALE_DO_UI_LEFT_COMMON_UI_INPUT_MQH_INCLUDED
#define ALE_DO_UI_LEFT_COMMON_UI_INPUT_MQH_INCLUDED

void UI_Input_Draw(const string name)
  {
  }

#endif // ALE_DO_UI_LEFT_COMMON_UI_INPUT_MQH_INCLUDED
