#property strict
#property script_show_inputs
#include "../../../Include/Config.mqh"
#include "../../../Include/Types.mqh"
#include "../../../Include/LotUtils.mqh"
#include "../../../Include/BrokerMoneyModel.mqh"
#include "../../../Include/HybridRoundingModel.mqh"
#include "../../../Include/HybridCatchUpModel.mqh"
int dimensionPassed=0,dimensionFailed=0;
void DimCheck(string id,bool ok){if(ok){dimensionPassed++;Print("CATCHUP_DIMENSION_TEST|ID=",id,"|PASS");}else{dimensionFailed++;Print("CATCHUP_DIMENSION_TEST|ID=",id,"|FAIL|Expected=PASS|Actual=FAIL");}}
void PrintEvaluatorDiagnostic(const HybridCatchUpOutcome outcome,const HybridHarvestLevelResult &r)
{
 Print("CATCHUP_DIMENSION_EVALUATOR|Outcome=",(int)outcome,"|ReasonCode=",r.reasonCode,"|Reason=",r.reason,"|PartialBudgetGross=",r.partialBudgetGross,"|FullFarLoss=",r.fullFarLoss,"|FarLotBefore=",r.farLotBefore,"|FarLotClosed=",r.farLotClosed,"|FarLotAfter=",r.farLotAfter,"|HarvestNet=",r.harvestNet,"|PartialAdd=",r.partialAdd,"|ReserveAdd=",r.reserveAdd,"|CarryAdd=",r.carryAdd,"|CoverageDeficit=",r.coverageDeficit,"|RecoveryAfterReopen=",r.recoveryAfterReopen,"|MarginLevelAfter=",r.marginLevelAfter,"|MarginUsageAfter=",r.marginUsageAfter);
}
bool BuildDimensionState(string symbol,double bid,double ask,double point,double minLot,double step,HybridCatchUpProfile &profile,HybridCatchUpState &state)
{
 ZeroMemory(profile);profile.kind=HYBRID_CATCHUP_BASE;ZeroMemory(state);state.levelIndex=0;state.symbol=symbol;state.magic=77;state.cycleId=9124;state.stateRevision=1;state.farDirection=DIR_BUY;state.bigDirection=DIR_SELL;state.smallDirection=DIR_BUY;
 state.farLot=NormalizeHybridCoreLot(MathMax(minLot,100.0*step));state.coreLot=NormalizeHybridCoreLot(state.farLot*BigCoreRatio);state.trendLot=NormalizeHybridTrendLot(state.farLot*BigTrendRatio);state.smallLot=NormalizeHybridSmallLot(state.farLot*SmallBaseToFarRatio);
 state.anchorBid=bid;state.anchorAsk=ask;state.anchorMid=(bid+ask)/2.0;state.baselineSpread=ask-bid;HybridReopenPrices prices;if(!BuildProjectedReopenPrices(state.bigDirection,bid,ask,prices))return false;state.coreOpenPrice=prices.coreOpenPrice;state.trendOpenPrice=prices.trendOpenPrice;state.smallOpenPrice=prices.smallOpenPrice;
 state.farOpenPrice=ask+(BigMoveStartPoints+BigMoveStepPoints)*point;state.realizedCyclePL=100000;state.finalReserveReal=100000;state.carryAvailable=0;state.equity=1000000;state.currentMargin=100;state.freeMargin=999900;state.lastCoverageDeficit=DBL_MAX;state.lastRecoveryPL=-DBL_MAX;state.fingerprint=HybridCatchUpFingerprint(state,profile.kind);
 return HybridLotGreaterOrEqual(symbol,state.farLot,minLot)&&HybridLotGreaterOrEqual(symbol,state.coreLot,minLot)&&HybridLotGreaterOrEqual(symbol,state.trendLot,minLot)&&HybridLotGreaterOrEqual(symbol,state.smallLot,minLot);
}
void OnStart()
{
 string symbol=_Symbol;double bid=SymbolInfoDouble(symbol,SYMBOL_BID),ask=SymbolInfoDouble(symbol,SYMBOL_ASK),point=SymbolInfoDouble(symbol,SYMBOL_POINT),minLot=SymbolInfoDouble(symbol,SYMBOL_VOLUME_MIN),volumeStep=SymbolInfoDouble(symbol,SYMBOL_VOLUME_STEP);int digits=(int)SymbolInfoInteger(symbol,SYMBOL_DIGITS);
 bool props=bid>0&&ask>=bid&&point>0&&minLot>0&&volumeStep>0&&digits>0;DimCheck("MQL-DIM-PROPERTIES",props);if(!props){Print("CATCHUP_DIMENSION_TEST|SUMMARY|Passed=",dimensionPassed,"|Failed=",dimensionFailed);return;}
 double tol=HybridLotTolerance(symbol);DimCheck("MQL-DIM-01",HybridLotLess(symbol,minLot-tol*2,minLot));DimCheck("MQL-DIM-02",!HybridLotEqual(symbol,10*volumeStep,9*volumeStep));DimCheck("MQL-DIM-03",HybridLotEqual(symbol,10*volumeStep,10*volumeStep+1e-10));DimCheck("MQL-DIM-04",!HybridPriceEqual(symbol,bid,bid+point));DimCheck("MQL-DIM-05",HybridRatioLess(0.99,1.0));DimCheck("MQL-DIM-06",HybridPercentGreaterOrEqual(200-HybridPercentTolerance()/2,200));DimCheck("MQL-DIM-07",HybridPercentLessOrEqual(50+HybridPercentTolerance()/2,50));DimCheck("MQL-DIM-08",!HybridLotGreater(symbol,tol/2,0));DimCheck("MQL-DIM-09",HybridLotGreaterOrEqual(symbol,10*volumeStep,10*volumeStep));
 HybridHarvestLevelResult b,w;ZeroMemory(b);ZeroMemory(w);b.triggerBid=bid;b.triggerAsk=ask;w.triggerBid=bid-point;w.triggerAsk=ask+point;DimCheck("MQL-DIM-10",HybridWorstCurrentLegsAreAdverse(symbol,b,w));DimCheck("MQL-DIM-11",!HybridLotLessOrEqual(symbol,11*volumeStep,10*volumeStep));DimCheck("MQL-DIM-12",HybridLotLess(symbol,9*volumeStep,10*volumeStep));
 double noisePartial=tol/2,realPartial=MathMax(volumeStep,tol*2);DimCheck("MQL-DIM-PARTIAL-01",!HybridLotGreater(symbol,noisePartial,0));DimCheck("MQL-DIM-PARTIAL-02",HybridLotGreater(symbol,realPartial,0));
 HybridCatchUpProfile profile;HybridCatchUpState initial;if(!BuildDimensionState(symbol,bid,ask,point,minLot,volumeStep,profile,initial)){DimCheck("MQL-DIM-EVAL-FIXTURE-NOT-FOUND",false);Print("CATCHUP_DIMENSION_TEST|SUMMARY|Passed=",dimensionPassed,"|Failed=",dimensionFailed);return;}
 double triggerBid,triggerAsk;BuildCatchUpBaseTrigger(initial,BigMoveStartPoints,triggerBid,triggerAsk);HybridPartialFarPreviewResult fullPreview;initial.partialFarBudgetAvailable=0;SolveHybridPartialFarPreview(initial,0,triggerBid,triggerAsk,fullPreview);
 bool found=false;HybridHarvestLevelResult row;HybridCatchUpState after;HybridCatchUpOutcome outcome=HYBRID_CATCHUP_OUTCOME_NOT_EVALUATED;
 for(int i=1;i<=16&&!found;i++){HybridCatchUpState candidate=initial;candidate.partialFarBudgetAvailable=HybridCatchUpMoneyRound(fullPreview.fullFarLoss*(i*5.0/100.0));candidate.fingerprint=HybridCatchUpFingerprint(candidate,profile.kind);outcome=EvaluateHybridCatchUpLevel(candidate,profile,row,after);bool continuationOutcome=outcome==HYBRID_CATCHUP_OUTCOME_CONTINUE||outcome==HYBRID_CATCHUP_OUTCOME_FINITE_PASS;found=continuationOutcome&&row.currentLegMoneyEvaluated&&row.harvestAllocationEvaluated&&row.fullFarAffordabilityEvaluated&&row.partialFarEvaluated&&row.partialBudgetPass&&row.allocationPass&&row.nextBasketEvaluated&&row.nextBasketGeometryEvaluated&&row.nextBasketMarginEvaluated&&row.recoveryAfterReopenEvaluated&&row.continuationStateValid&&HybridLotGreater(symbol,row.farLotClosed,0)&&HybridLotLess(symbol,row.farLotAfter,row.farLotBefore)&&!row.finalClosePreviewRouteCandidate&&!row.finalClosePreviewRequired&&!row.finalCloseRouteState.routeCandidate;if(!found)PrintEvaluatorDiagnostic(outcome,row);}
 DimCheck("MQL-DIM-EVAL-FIXTURE-NOT-FOUND",found);DimCheck("MQL-DIM-EVAL-OUTCOME",found&&(outcome==HYBRID_CATCHUP_OUTCOME_CONTINUE||outcome==HYBRID_CATCHUP_OUTCOME_FINITE_PASS));DimCheck("MQL-DIM-EVAL-PARTIAL",found&&row.partialFarEvaluated);DimCheck("MQL-DIM-EVAL-NEXT-BASKET",found&&row.nextBasketEvaluated);DimCheck("MQL-DIM-EVAL-GEOMETRY",found&&row.nextBasketGeometryEvaluated);DimCheck("MQL-DIM-EVAL-MARGIN",found&&row.nextBasketMarginEvaluated);DimCheck("MQL-DIM-EVAL-RECOVERY",found&&row.recoveryAfterReopenEvaluated);DimCheck("MQL-DIM-EVAL-STATE",found&&row.continuationStateValid);DimCheck("MQL-DIM-EVAL-AFTER-FAR",found&&HybridLotLessOrEqual(symbol,after.farLot,initial.farLot));DimCheck("MQL-DIM-EVAL-NO-ROUTE",found&&!row.finalClosePreviewRouteCandidate&&!row.finalClosePreviewRequired&&!row.finalCloseRouteState.routeCandidate);
 Print("CATCHUP_DIMENSION_TEST|SUMMARY|Passed=",dimensionPassed,"|Failed=",dimensionFailed);
}
