#ifndef HSBI_BASKET_MONEY_EVALUATOR_MQH
#define HSBI_BASKET_MONEY_EVALUATOR_MQH
#include "HSBI_LevelMarginEvaluator.mqh"
#include "../Planning/HSBI_ControlPrices.mqh"
struct HSBI_BasketMoneyInput{double farVolume;double coreVolume;double trendVolume;double smallVolume;HSBI_Direction farDirection;string symbol;HSBI_BrokerProperties broker;HSBI_ControlPrice controlPrice;double farOpenPrice;double coreOpenPrice;double trendOpenPrice;double smallOpenPrice;HSBI_CostSnapshot farCosts;HSBI_CostSnapshot coreCosts;HSBI_CostSnapshot trendCosts;HSBI_CostSnapshot smallCosts;double executionSafetyBuffer;ulong snapshotId;};
struct HSBI_BasketMoneyResult{HSBI_CalculationStatus status;bool valid;bool brokerRuntimeConfirmed;HSBI_BrokerMoneyEvaluationResult far;HSBI_BrokerMoneyEvaluationResult core;HSBI_BrokerMoneyEvaluationResult trend;HSBI_BrokerMoneyEvaluationResult small;double basketNetMoney;double recoveryMoney;double totalMargin;double grossExposure;double reserveGainMoney;double farLossIncreaseMoney;double transitionLoss;double safetyBuffer;HSBI_ReasonCode reason;string details;};
HSBI_BrokerMoneyEvaluationInput HSBI_BasketLegInput(const HSBI_BasketMoneyInput &x,const HSBI_Direction direction,const double volume,const double openPrice,const HSBI_CostSnapshot &cost)
{
   HSBI_BrokerMoneyEvaluationInput leg;ZeroMemory(leg);leg.broker=x.broker;leg.symbol=x.symbol;leg.direction=direction;leg.volume=volume;leg.openPrice=openPrice;leg.bid=x.controlPrice.bid;leg.ask=x.controlPrice.ask;leg.closePrice=(direction==HSBI_DIRECTION_BUY?leg.bid:leg.ask);leg.costs=cost;leg.executionSafetyBuffer=x.executionSafetyBuffer;leg.snapshotId=x.snapshotId;leg.timestamp=x.controlPrice.timestamp;leg.projected=true;return leg;
}
HSBI_BasketMoneyResult HSBI_EvaluateBasketMoney(const HSBI_BasketMoneyInput &x)
{
   HSBI_BasketMoneyResult r;ZeroMemory(r);r.status=HSBI_CALC_REJECT;r.reason=HSBI_REASON_INTERNAL_INVARIANT_FAILED;r.details="INVALID_BASKET";if(x.farDirection!=HSBI_DIRECTION_BUY&&x.farDirection!=HSBI_DIRECTION_SELL)return r;if(!HSBI_ValidateTypedControlPrice(x.controlPrice,x.symbol))return r;
   HSBI_Direction opposite=(x.farDirection==HSBI_DIRECTION_BUY?HSBI_DIRECTION_SELL:HSBI_DIRECTION_BUY);HSBI_BrokerMoneyEvaluationInput farIn=HSBI_BasketLegInput(x,x.farDirection,x.farVolume,x.farOpenPrice,x.farCosts),coreIn=HSBI_BasketLegInput(x,opposite,x.coreVolume,x.coreOpenPrice,x.coreCosts),trendIn=HSBI_BasketLegInput(x,opposite,x.trendVolume,x.trendOpenPrice,x.trendCosts),smallIn=HSBI_BasketLegInput(x,x.farDirection,x.smallVolume,x.smallOpenPrice,x.smallCosts);
   r.far=HSBI_EvaluateProjectedLegMoney(farIn);r.core=HSBI_EvaluateProjectedLegMoney(coreIn);r.trend=HSBI_EvaluateProjectedLegMoney(trendIn);r.small=HSBI_EvaluateProjectedLegMoney(smallIn);if(!r.far.valid||!r.core.valid||!r.trend.valid||!r.small.valid){r.status=(r.far.status==HSBI_CALC_UNAVAILABLE||r.core.status==HSBI_CALC_UNAVAILABLE||r.trend.status==HSBI_CALC_UNAVAILABLE||r.small.status==HSBI_CALC_UNAVAILABLE)?HSBI_CALC_UNAVAILABLE:HSBI_CALC_REJECT;r.details="LEG_MONEY_UNAVAILABLE";return r;}
   HSBI_MarginCalculationResult fm=HSBI_EvaluateProjectedLegMargin(farIn),cm=HSBI_EvaluateProjectedLegMargin(coreIn),tm=HSBI_EvaluateProjectedLegMargin(trendIn),sm=HSBI_EvaluateProjectedLegMargin(smallIn);if(!fm.valid||!cm.valid||!tm.valid||!sm.valid){r.status=(fm.status==HSBI_CALC_UNAVAILABLE||cm.status==HSBI_CALC_UNAVAILABLE||tm.status==HSBI_CALC_UNAVAILABLE||sm.status==HSBI_CALC_UNAVAILABLE)?HSBI_CALC_UNAVAILABLE:HSBI_CALC_REJECT;r.details="LEG_MARGIN_UNAVAILABLE";return r;}
   r.basketNetMoney=r.far.netMoney+r.core.netMoney+r.trend.netMoney+r.small.netMoney;r.recoveryMoney=r.basketNetMoney;r.totalMargin=fm.margin+cm.margin+tm.margin+sm.margin;r.grossExposure=x.farVolume+x.coreVolume+x.trendVolume+x.smallVolume;r.reserveGainMoney=MathMax(0.0,r.core.netMoney+r.trend.netMoney+r.small.netMoney);r.farLossIncreaseMoney=MathMax(0.0,-r.far.netMoney);r.transitionLoss=MathMax(0.0,-r.basketNetMoney);r.safetyBuffer=x.executionSafetyBuffer*4.0;
   if(!HSBI_IsFiniteNumber(r.basketNetMoney)||!HSBI_IsFiniteNumber(r.totalMargin)||!HSBI_IsFiniteNumber(r.grossExposure)){r.status=HSBI_CALC_ERROR;r.details="NONFINITE_BASKET";return r;}r.status=HSBI_CALC_PASS;r.valid=true;r.brokerRuntimeConfirmed=true;r.reason=HSBI_REASON_OK;r.details="PASS";return r;
}
#endif
