#ifndef ALE_DO_SUCCESS_SUCCESSCODES_MQH_INCLUDED
#define ALE_DO_SUCCESS_SUCCESSCODES_MQH_INCLUDED

enum SuccessCode
  {
   SUCCESS_NONE = 0,
   SUCCESS_GENERIC = 1
  };

#endif // ALE_DO_SUCCESS_SUCCESSCODES_MQH_INCLUDED
