#ifndef ALE_DO_CORE_GEOMETRY_GEOMETRY_SEQUENCEVALIDATOR_MQH_INCLUDED
#define ALE_DO_CORE_GEOMETRY_GEOMETRY_SEQUENCEVALIDATOR_MQH_INCLUDED

bool Geometry_ValidateSequence()
  {
   return(true);
  }

#endif // ALE_DO_CORE_GEOMETRY_GEOMETRY_SEQUENCEVALIDATOR_MQH_INCLUDED
