#ifndef HSBI_VERSION_MQH
#define HSBI_VERSION_MQH
#define HSBI_PROJECT_NAME "Hybrid_Split_Big_Independent_EA"
#define HSBI_PROJECT_GENERATION 1
#define HSBI_STAGE "HSB.1"
#define HSBI_SCHEMA_VERSION 1
#define HSBI_MONEY_STATE_VERSION 1
#define HSBI_EVENT_SCHEMA_VERSION 1
#define HSBI_SNAPSHOT_SCHEMA_VERSION 1
#define HSBI_TRADING_IMPLEMENTED false
#define HSBI_REAL_TRADING_ALLOWED false
#endif