#ifndef HSBI_STATE_MACHINE_MQH
#define HSBI_STATE_MACHINE_MQH
#include "HSBI_Context.mqh"
struct HSBI_StateTransitionResult{bool allowed;HSBI_State fromState;HSBI_State toState;ulong proposedRevision;HSBI_ReasonCode reason;};
bool HSBI_IsTransitionAllowed(const HSBI_State from,const HSBI_State to){if(from==to)return true;if(from==HSBI_STATE_DISABLED&&to==HSBI_STATE_IDLE)return true;if(from==HSBI_STATE_IDLE&&to==HSBI_STATE_INITIAL_PLAN_READY)return true;if(from==HSBI_STATE_INITIAL_PLAN_READY&&to==HSBI_STATE_INITIAL_OPENING_BUY)return true;if(from==HSBI_STATE_INITIAL_OPENING_BUY&&to==HSBI_STATE_INITIAL_OPENING_SELL)return true;if(from==HSBI_STATE_INITIAL_OPENING_SELL&&to==HSBI_STATE_INITIAL_LOCK_ACTIVE)return true;if(from==HSBI_STATE_INITIAL_LOCK_ACTIVE&&to==HSBI_STATE_INITIAL_PLUS_CLOSING)return true;if(from==HSBI_STATE_INITIAL_PLUS_CLOSING&&to==HSBI_STATE_FAR_ACTIVE)return true;if(from==HSBI_STATE_FAR_ACTIVE&&to==HSBI_STATE_CANDIDATE_PLANNED)return true;if(from==HSBI_STATE_CANDIDATE_PLANNED&&to==HSBI_STATE_BASKET_OPENING_CORE)return true;if(from==HSBI_STATE_RECONCILING&&(to==HSBI_STATE_TERMINAL_SAFE||to==HSBI_STATE_FAR_ACTIVE||to==HSBI_STATE_IDLE))return true;if(to==HSBI_STATE_RECONCILING||to==HSBI_STATE_TERMINAL_SAFE||to==HSBI_STATE_EMERGENCY)return true;return false;}
HSBI_StateTransitionResult HSBI_ProposeStateTransition(const HSBI_RecoveryContext &c,const HSBI_State to){HSBI_StateTransitionResult r;r.fromState=c.currentState;r.toState=to;r.allowed=HSBI_IsTransitionAllowed(c.currentState,to);r.proposedRevision=c.stateRevision+(r.allowed?1:0);r.reason=r.allowed?HSBI_REASON_OK:HSBI_REASON_INVALID_STATE_TRANSITION;return r;}
bool HSBI_ApplyPureStateTransition(HSBI_RecoveryContext &c,const HSBI_State to){HSBI_StateTransitionResult r=HSBI_ProposeStateTransition(c,to);if(!r.allowed)return false;c.previousState=c.currentState;c.currentState=to;c.stateRevision=r.proposedRevision;return true;}
HSBI_State HSBI_ConflictTargetState(){return HSBI_STATE_RECONCILING;}
HSBI_State HSBI_CriticalErrorTargetState(const bool unresolved){return unresolved?HSBI_STATE_TERMINAL_SAFE:HSBI_STATE_EMERGENCY;}
#endif
