#ifndef ALE_DO_CORE_FLOW_COMMON_GEOMETRYCONTEXT_MQH_INCLUDED
#define ALE_DO_CORE_FLOW_COMMON_GEOMETRYCONTEXT_MQH_INCLUDED

struct GeometryContext
  {
   double anchor_price;
   double market_price;
  };

#endif // ALE_DO_CORE_FLOW_COMMON_GEOMETRYCONTEXT_MQH_INCLUDED
