#ifndef ALE_DO_TESTS_TEST_INVARIANTS_MQH_INCLUDED
#define ALE_DO_TESTS_TEST_INVARIANTS_MQH_INCLUDED

bool Test_Invariants_Run()
  {
   return(true);
  }

#endif // ALE_DO_TESTS_TEST_INVARIANTS_MQH_INCLUDED
