#ifndef ALE_DO_TESTS_TEST_SAFE_MODE_MQH_INCLUDED
#define ALE_DO_TESTS_TEST_SAFE_MODE_MQH_INCLUDED

bool Test_SAFE_Mode_Run()
  {
   return(true);
  }

#endif // ALE_DO_TESTS_TEST_SAFE_MODE_MQH_INCLUDED
