#ifndef ALE_DO_UI_LEFT_COMMON_UI_BUTTON_MQH_INCLUDED
#define ALE_DO_UI_LEFT_COMMON_UI_BUTTON_MQH_INCLUDED

void UI_Button_Draw(const string label)
  {
  }

#endif // ALE_DO_UI_LEFT_COMMON_UI_BUTTON_MQH_INCLUDED
