#ifndef ALE_DO_UI_LEFT_COMMON_UI_ICONS_MQH_INCLUDED
#define ALE_DO_UI_LEFT_COMMON_UI_ICONS_MQH_INCLUDED

void UI_Icons_Draw(const string name)
  {
  }

#endif // ALE_DO_UI_LEFT_COMMON_UI_ICONS_MQH_INCLUDED
