#ifndef ALE_DO_UI_LEFT_COMMON_UI_TABLE_MQH_INCLUDED
#define ALE_DO_UI_LEFT_COMMON_UI_TABLE_MQH_INCLUDED

void UI_Table_Draw(const string name)
  {
  }

#endif // ALE_DO_UI_LEFT_COMMON_UI_TABLE_MQH_INCLUDED
