#ifndef ALE_DO_CORE_INVARIANTS_INVARIANT_MARGIN_MQH_INCLUDED
#define ALE_DO_CORE_INVARIANTS_INVARIANT_MARGIN_MQH_INCLUDED

bool Invariant_CheckMargin()
  {
   return(true);
  }

#endif // ALE_DO_CORE_INVARIANTS_INVARIANT_MARGIN_MQH_INCLUDED
