#ifndef ALE_DO_CORE_INVARIANTS_INVARIANT_GEOMETRY_MQH_INCLUDED
#define ALE_DO_CORE_INVARIANTS_INVARIANT_GEOMETRY_MQH_INCLUDED

bool Invariant_CheckGeometry()
  {
   return(true);
  }

#endif // ALE_DO_CORE_INVARIANTS_INVARIANT_GEOMETRY_MQH_INCLUDED
