#ifndef ALE_DO_CORE_INVARIANTS_INVARIANT_ORDERING_MQH_INCLUDED
#define ALE_DO_CORE_INVARIANTS_INVARIANT_ORDERING_MQH_INCLUDED

bool Invariant_CheckOrdering()
  {
   return(true);
  }

#endif // ALE_DO_CORE_INVARIANTS_INVARIANT_ORDERING_MQH_INCLUDED
