#ifndef HSBI_NEW_FAR_SOLVER_MQH
#define HSBI_NEW_FAR_SOLVER_MQH
#include "HSBI_NewFarCandidate.mqh"
#include "HSBI_FutureSmallSolver.mqh"
#include "../Execution/HSBI_OwnershipGuardTypes.mqh"
#include "../Risk/HSBI_NewFarGateTypes.mqh"
#include "../Money/HSBI_CatchUpModel.mqh"
enum HSBI_SolverStatus{HSBI_SOLVER_SELECTED,HSBI_SOLVER_NO_SAFE_CANDIDATE,HSBI_SOLVER_SOURCE_MISMATCH,HSBI_SOLVER_STALE_SNAPSHOT,HSBI_SOLVER_PROOF_FAILED,HSBI_SOLVER_MARGIN_FAILED,HSBI_SOLVER_RISK_FAILED,HSBI_SOLVER_TRANSITION_LOSS_FAILED,HSBI_SOLVER_BROKER_GRID_FAILED,HSBI_SOLVER_RECONCILIATION_REQUIRED,HSBI_SOLVER_TERMINAL_SAFE};
struct HSBI_TransitionPlanSnapshot{ulong planId;ulong stateRevision;bool immutable;bool persisted;};
struct HSBI_ActualClosingDealsSnapshot{ulong sourceDealId;bool fillsConfirmed;bool actual;};
struct HSBI_AllocationStateSnapshot{bool valid;bool fresh;ulong revision;};
struct HSBI_NewFarSolverInput{HSBI_PositionDescriptor oldFarDescriptor;HSBI_PositionDescriptor originalBigCoreDescriptor;HSBI_PositionDescriptor actualBigCoreResidual;HSBI_TransitionPlanSnapshot smallTransitionPlan;HSBI_ActualClosingDealsSnapshot actualClosingDeals;HSBI_MoneyStateSnapshot moneyState;HSBI_AllocationStateSnapshot allocationState;HSBI_RiskSnapshot riskState;HSBI_MarginSnapshot marginState;HSBI_ControlPriceSnapshot controlPrice;HSBI_BrokerProperties brokerProperties;HSBI_FutureSmallResult futureSmallProof;ulong cycleId;ulong planId;ulong stateRevision;double projectedVolume;double maximumNewFarRatio;double minimumCompressionLots;double minimumCompressionRatio;double coreRatio;double trendRatio;double smallRatio;double reserveShare;double reserveGainPerLot;double farLossPerLot;double riskTolerance;double marginPerLot;double riskImprovementPerLot;double transitionLossPerLot;double absoluteLossCap;double equityPercentCap;double oldFarRiskCap;double cumulativeCycleLossCap;double grossExposurePerLot;double safetyBufferMoney;bool brokerMoneyAvailable;bool secondFarPresent;string expectedPlanDigest;};
struct HSBI_NewFarSolverResult{bool valid;HSBI_SolverStatus status;double selectedVolume;double oldFarVolume;double actualResidualVolume;double projectedVolume;double compressionLots;double compressionRatio;double riskNext;double marginNext;double transitionLoss;double allowedTransitionLoss;int candidateCount;int rejectedCandidateCount;ulong sourceIdentifier;ulong sourceDealId;ulong planId;ulong stateRevision;string candidateDigest;string proofDigest;HSBI_ReasonCode reason;string details;};
string HSBI_NewFarInputDigest(const HSBI_NewFarSolverInput &x){return LongToString(x.oldFarDescriptor.identity.accountLogin)+"|"+x.oldFarDescriptor.identity.symbol+"|"+LongToString(x.oldFarDescriptor.identity.magic)+"|"+HSBI_UlongToString(x.cycleId)+"|"+HSBI_UlongToString(x.stateRevision)+"|"+HSBI_UlongToString(x.planId)+"|"+DoubleToString(x.oldFarDescriptor.actualVolume,8)+"|"+HSBI_UlongToString(x.originalBigCoreDescriptor.identifier)+"|"+DoubleToString(x.actualBigCoreResidual.actualVolume,8)+"|"+DoubleToString(x.projectedVolume,8)+"|"+DoubleToString(x.maximumNewFarRatio,8)+"|"+DoubleToString(x.minimumCompressionLots,8)+"|"+DoubleToString(x.minimumCompressionRatio,8)+"|"+DoubleToString(x.coreRatio,8)+"|"+DoubleToString(x.trendRatio,8)+"|"+DoubleToString(x.smallRatio,8)+"|"+DoubleToString(x.brokerProperties.volumeStep,8)+"|"+DoubleToString(x.controlPrice.selectedPrice,8)+"|"+x.futureSmallProof.proofDigest+"|"+HSBI_UlongToString(x.riskState.snapshotId)+"|"+HSBI_UlongToString(x.marginState.snapshotId);}
bool HSBI_ValidateNewFarSource(const HSBI_NewFarSolverInput &x)
{
   if(!x.actualClosingDeals.actual||!x.actualClosingDeals.fillsConfirmed||x.actualClosingDeals.sourceDealId==0)return false;
   if(x.oldFarDescriptor.role!=HSBI_ROLE_FAR||x.originalBigCoreDescriptor.role!=HSBI_ROLE_BIG_CORE||x.actualBigCoreResidual.role!=HSBI_ROLE_BIG_CORE)return false;
   if(!HSBI_SamePositionOwner(x.originalBigCoreDescriptor.identity,x.actualBigCoreResidual.identity))return false;
   if(x.originalBigCoreDescriptor.identity.accountLogin!=x.oldFarDescriptor.identity.accountLogin||x.originalBigCoreDescriptor.identity.symbol!=x.oldFarDescriptor.identity.symbol||x.originalBigCoreDescriptor.identity.magic!=x.oldFarDescriptor.identity.magic||x.originalBigCoreDescriptor.identity.cycleId!=x.cycleId)return false;
   if(x.originalBigCoreDescriptor.identifier==0||x.originalBigCoreDescriptor.identifier!=x.actualBigCoreResidual.identifier||x.originalBigCoreDescriptor.ticket==0||x.originalBigCoreDescriptor.ticket!=x.actualBigCoreResidual.ticket)return false;
   if(x.oldFarDescriptor.direction==HSBI_DIRECTION_NONE||x.actualBigCoreResidual.direction==HSBI_DIRECTION_NONE||x.oldFarDescriptor.direction==x.actualBigCoreResidual.direction||x.actualBigCoreResidual.actualVolume<=0.0||x.actualBigCoreResidual.actualVolume>=x.oldFarDescriptor.actualVolume)return false;
   return HSBI_IsActualBigCoreResidual(x.actualBigCoreResidual,x.originalBigCoreDescriptor.identifier)&&HSBI_ValidateVolume(x.actualBigCoreResidual.actualVolume,x.brokerProperties);
}
double HSBI_AllowedTransitionLoss(const HSBI_NewFarSolverInput &x){return MathMin(MathMin(x.absoluteLossCap,x.equityPercentCap),MathMin(x.oldFarRiskCap,x.cumulativeCycleLossCap));}
HSBI_NewFarSolverResult HSBI_SolveNewFar(const HSBI_NewFarSolverInput &x)
{
   HSBI_NewFarSolverResult r;ZeroMemory(r);r.status=HSBI_SOLVER_NO_SAFE_CANDIDATE;r.reason=HSBI_REASON_INTERNAL_INVARIANT_FAILED;r.oldFarVolume=x.oldFarDescriptor.actualVolume;r.actualResidualVolume=x.actualBigCoreResidual.actualVolume;r.projectedVolume=x.projectedVolume;r.planId=x.planId;r.stateRevision=x.stateRevision;r.sourceIdentifier=x.originalBigCoreDescriptor.identifier;r.sourceDealId=x.actualClosingDeals.sourceDealId;r.details="NO_SAFE_CANDIDATE";
   if(!x.controlPrice.fresh||!x.riskState.fresh||!x.marginState.fresh||!x.moneyState.fresh||!x.allocationState.fresh){r.status=HSBI_SOLVER_STALE_SNAPSHOT;r.details="STALE_SNAPSHOT";return r;}
   if(x.secondFarPresent){r.status=HSBI_SOLVER_RECONCILIATION_REQUIRED;r.details="SECOND_FAR";return r;}
   if(!HSBI_ValidateNewFarSource(x)){r.status=HSBI_SOLVER_SOURCE_MISMATCH;r.reason=HSBI_REASON_INVALID_IDENTITY;r.details="NEW_FAR_SOURCE_MISMATCH";return r;}
   if(!x.futureSmallProof.valid||!x.brokerMoneyAvailable){r.status=HSBI_SOLVER_PROOF_FAILED;r.details="PROOF_OR_MONEY_UNAVAILABLE";return r;}
   if(x.planId==0||x.stateRevision==0||x.smallTransitionPlan.planId!=x.planId||x.smallTransitionPlan.stateRevision!=x.stateRevision||!x.smallTransitionPlan.immutable||!x.smallTransitionPlan.persisted){r.status=HSBI_SOLVER_RECONCILIATION_REQUIRED;r.details="PLAN_IDENTITY_MISMATCH";return r;}
   string inputDigest=HSBI_NewFarInputDigest(x);if(x.expectedPlanDigest!=""&&x.expectedPlanDigest!=inputDigest){r.status=HSBI_SOLVER_RECONCILIATION_REQUIRED;r.details="PLAN_DIGEST_MISMATCH";return r;}
   r.allowedTransitionLoss=HSBI_AllowedTransitionLoss(x);if(!HSBI_IsFiniteNumber(r.allowedTransitionLoss)||r.allowedTransitionLoss<0.0){r.status=HSBI_SOLVER_TRANSITION_LOSS_FAILED;r.details="TRANSITION_CAP_UNAVAILABLE";return r;}
   HSBI_NewFarCandidate safe[];int safeCount=0;double upper=MathMin(x.brokerProperties.volumeMax,x.actualBigCoreResidual.actualVolume);
   for(double n=x.brokerProperties.volumeMin;n<=upper+HSBI_GridTolerance(x.brokerProperties.volumeStep);n+=x.brokerProperties.volumeStep)
   {
      r.candidateCount++;double candidate=HSBI_NormalizeVolume(n,x.brokerProperties.volumeStep,HSBI_VOLUME_PARTIAL_FAR);double compression=x.oldFarDescriptor.actualVolume-candidate;double ratio=compression/x.oldFarDescriptor.actualVolume;
      if(!HSBI_ValidateVolume(candidate,x.brokerProperties)||candidate<=0.0||candidate>=x.oldFarDescriptor.actualVolume||candidate>x.maximumNewFarRatio*x.oldFarDescriptor.actualVolume||compression<x.minimumCompressionLots||ratio<x.minimumCompressionRatio){r.rejectedCandidateCount++;continue;}
      HSBI_GeometryResult geometry=HSBI_SolveBigGeometry(candidate,x.coreRatio,x.trendRatio,x.smallRatio,x.brokerProperties,true,true);if(!geometry.valid){r.rejectedCandidateCount++;continue;}
      HSBI_CatchUpInput catchUp;ZeroMemory(catchUp);catchUp.reserveShare=x.reserveShare;catchUp.netBigVolume=geometry.netBigVolume;catchUp.farVolume=candidate;catchUp.reserveGainMoney=x.reserveGainPerLot*geometry.netBigVolume;catchUp.farLossIncreaseMoney=x.farLossPerLot*candidate;catchUp.executionSafetyBuffer=x.safetyBufferMoney;catchUp.farDirection=x.oldFarDescriptor.direction;catchUp.moneyAvailable=x.brokerMoneyAvailable;catchUp.snapshotFresh=x.controlPrice.fresh;if(!HSBI_EvaluateCatchUp(catchUp).passed){r.rejectedCandidateCount++;continue;}
      double marginNext=x.marginPerLot*candidate;double riskNext=x.riskState.currentRisk-x.riskImprovementPerLot*compression;double loss=x.transitionLossPerLot*MathAbs(x.actualBigCoreResidual.actualVolume-candidate);double grossNext=x.grossExposurePerLot*candidate;
      HSBI_NewFarGateInput gate;ZeroMemory(gate);gate.marginNext=marginNext;gate.allowedMargin=x.marginState.allowedMargin;gate.riskNext=riskNext;gate.riskOld=x.riskState.currentRisk;gate.riskTolerance=x.riskTolerance;gate.grossExposureNext=grossNext;gate.grossExposureOld=x.riskState.currentGrossExposure;gate.transitionLoss=loss;gate.absoluteLossCap=x.absoluteLossCap;gate.equityPercentCap=x.equityPercentCap;gate.oldFarRiskCap=x.oldFarRiskCap;gate.cumulativeCycleLossCap=x.cumulativeCycleLossCap;gate.marginAvailable=x.marginState.available;gate.riskAvailable=x.riskState.available;gate.transitionCapAvailable=true;gate.moneyAvailable=x.brokerMoneyAvailable;gate.snapshotFresh=x.controlPrice.fresh;HSBI_NewFarGateResult gated=HSBI_EvaluateNewFarGates(gate);if(!gated.passed){r.rejectedCandidateCount++;continue;}
      HSBI_NewFarCandidate c;ZeroMemory(c);c.candidateVolume=n;c.normalizedVolume=candidate;c.oldFarVolume=x.oldFarDescriptor.actualVolume;c.compressionLots=compression;c.compressionRatio=ratio;c.riskNext=riskNext;c.marginNext=marginNext;c.futureSmallStatus=HSBI_STATUS_VALID;c.finiteCatchUpStatus=HSBI_STATUS_VALID;c.nextCycleFeasible=true;c.sourceBigCoreIdentifier=x.originalBigCoreDescriptor.identifier;c.sourceBigCoreTicket=x.originalBigCoreDescriptor.ticket;c.validationStatus=HSBI_STATUS_VALID;c.reason=HSBI_REASON_OK;c.futureTransitionCount=x.futureSmallProof.theoreticalDepth;c.safetyBuffer=x.safetyBufferMoney;c.candidateDigest=DoubleToString(candidate,8)+"|"+DoubleToString(riskNext,8)+"|"+DoubleToString(marginNext,8)+"|"+inputDigest;ArrayResize(safe,safeCount+1);safe[safeCount++]=c;
   }
   if(safeCount==0)return r;int best=0;for(int i=1;i<safeCount;i++)if(HSBI_CompareCandidateTieBreak(safe[i],safe[best])<0)best=i;
   HSBI_NewFarCandidate selected=safe[best];r.valid=true;r.status=HSBI_SOLVER_SELECTED;r.selectedVolume=selected.normalizedVolume;r.compressionLots=selected.compressionLots;r.compressionRatio=selected.compressionRatio;r.riskNext=selected.riskNext;r.marginNext=selected.marginNext;r.transitionLoss=x.transitionLossPerLot*MathAbs(x.actualBigCoreResidual.actualVolume-selected.normalizedVolume);r.candidateDigest=selected.candidateDigest;r.proofDigest=x.futureSmallProof.proofDigest;r.reason=HSBI_REASON_OK;r.details="SELECTED";return r;
}
#endif
