#ifndef HSBI_FUTURE_SMALL_SOLVER_MQH
#define HSBI_FUTURE_SMALL_SOLVER_MQH
#include "HSBI_FutureSmallTypes.mqh"
#include "../Risk/HSBI_FutureSmallRiskEvaluator.mqh"
bool HSBI_CalculateFutureSmallDepth(const double initialFar,const double volumeMin,const double q,const double volumeStep,int &depth){depth=0;if(!HSBI_IsFiniteNumber(initialFar)||!HSBI_IsFiniteNumber(volumeMin)||!HSBI_IsFiniteNumber(q)||!HSBI_IsFiniteNumber(volumeStep)||initialFar<=0.0||volumeMin<=0.0||volumeMin>initialFar||q<=0.0||q>=1.0||volumeStep<=0.0)return false;double value=MathLog(volumeMin/initialFar)/MathLog(q);if(!HSBI_IsFiniteNumber(value)||value<0.0||value>2147483647.0)return false;depth=(int)MathCeil(value);return true;}
bool HSBI_ValidateConservativeBound(const double initialFar,const double observedFar,const double q,const int exactDepth,const bool roundingIncluded,const bool costsIncluded,const bool marginIncluded,const bool riskIncluded,const bool transitionLossIncluded){if(exactDepth<2||q<=0.0||q>=1.0||!roundingIncluded||!costsIncluded||!marginIncluded||!riskIncluded||!transitionLossIncluded)return false;if(!HSBI_IsFiniteNumber(initialFar)||!HSBI_IsFiniteNumber(observedFar)||initialFar<=0.0||observedFar<=0.0)return false;return observedFar<=initialFar*MathPow(q,exactDepth)+1.0e-10;}
bool HSBI_ValidateFutureSmallInput(const HSBI_FutureSmallInput &x)
{
   if(x.testOnlyApproximation||!x.brokerPropertiesValid||!x.snapshotsFresh||!x.roundingIncluded||!x.costsIncluded)return false;
   if(!x.moneyState.available||!x.moneyState.fresh||!x.riskState.available||!x.riskState.fresh||!x.marginState.available||!x.marginState.fresh||!x.controlPrice.valid||!x.controlPrice.fresh)return false;
   if(HSBI_ValidateBrokerProperties(x.broker)!=HSBI_BROKER_PROPERTIES_VALID||!HSBI_ValidateTypedControlPrice(x.typedControlPrice,x.broker.symbol))return false;
   if(x.cycleId==0||x.stateRevision==0||x.planId==0||x.maximumDepth<1||x.maximumDepth>128||x.currentFar<=0.0||x.volumeStep<=0.0||x.conservativeQ<=0.0||x.conservativeQ>=1.0)return false;
   if(x.maxNewFarRatio<=0.0||x.maxNewFarRatio>=1.0||x.minimumCompressionLots<=0.0||x.minimumCompressionRatio<=0.0||x.minimumCompressionRatio>=1.0)return false;
   return x.farDirection==HSBI_DIRECTION_BUY||x.farDirection==HSBI_DIRECTION_SELL;
}
HSBI_FutureSmallLevelResult HSBI_EvaluateFutureSmallLevel(const HSBI_FutureSmallLevelInput &x)
{
   HSBI_FutureSmallLevelResult r;ZeroMemory(r);r.levelIndex=x.levelIndex;r.farBefore=x.farBefore;r.status=HSBI_FS_REJECTED;r.reason=HSBI_REASON_INTERNAL_INVARIANT_FAILED;r.details="LEVEL_REJECTED";if(x.testOnlyApproximation)return r;
   HSBI_GeometryResult g=HSBI_SolveBigGeometry(x.farBefore,x.coreRatio,x.trendRatio,x.smallRatio,x.broker,true,true);if(!g.valid){r.details="GEOMETRY_FAILED";return r;}r.coreVolume=g.coreVolume;r.trendVolume=g.trendVolume;r.smallVolume=g.smallVolume;r.netBigVolume=g.netBigVolume;r.recoverySlopeLots=g.recoverySlopeLots;r.farAfter=HSBI_FloorVolumeToStep(g.smallVolume,x.broker.volumeStep);r.compressionLots=x.farBefore-r.farAfter;r.compressionRatio=r.compressionLots/x.farBefore;
   if(r.farAfter<=0.0||r.farAfter>=x.farBefore||r.farAfter>x.maxNewFarRatio*x.farBefore+HSBI_GridTolerance(x.broker.volumeStep)||r.compressionLots<x.minimumCompressionLots-HSBI_GridTolerance(x.broker.volumeStep)||r.compressionRatio<x.minimumCompressionRatio-1.0e-10){r.details="COMPRESSION_FAILED";return r;}
   HSBI_BasketMoneyResult basket;if(x.useInjectedBrokerProof){basket=x.injectedBrokerProof;if(!basket.valid||!basket.brokerRuntimeConfirmed){r.details="INJECTED_PROOF_UNCONFIRMED";return r;}}else{HSBI_BasketMoneyInput bi;ZeroMemory(bi);bi.farVolume=x.farBefore;bi.coreVolume=g.coreVolume;bi.trendVolume=g.trendVolume;bi.smallVolume=g.smallVolume;bi.farDirection=(x.controlPrice.direction==HSBI_DIRECTION_NONE?HSBI_DIRECTION_SELL:x.controlPrice.direction);bi.symbol=x.broker.symbol;bi.broker=x.broker;bi.controlPrice=x.controlPrice;bi.farOpenPrice=x.farOpenPrice;bi.coreOpenPrice=x.coreOpenPrice;bi.trendOpenPrice=x.trendOpenPrice;bi.smallOpenPrice=x.smallOpenPrice;bi.farCosts=x.farCosts;bi.coreCosts=x.coreCosts;bi.trendCosts=x.trendCosts;bi.smallCosts=x.smallCosts;bi.executionSafetyBuffer=x.executionSafetyBuffer;bi.snapshotId=x.broker.snapshotId;basket=HSBI_EvaluateBasketMoney(bi);}
   r.basketProof=basket;if(!basket.valid){r.details="BROKER_MONEY_OR_MARGIN_UNAVAILABLE";return r;}HSBI_FutureSmallRiskResult risk=HSBI_EvaluateFutureSmallRisk(basket,x.riskState.currentRisk,x.riskState.riskTolerance,x.riskState.available);if(!risk.valid){r.details="RISK_UNAVAILABLE_OR_FAILED";return r;}
   r.recoveryMoney=basket.recoveryMoney;r.totalMargin=basket.totalMargin;r.grossExposure=basket.grossExposure;r.transitionLoss=basket.transitionLoss;r.riskValue=risk.riskValue;r.moneyIncluded=true;r.marginIncluded=true;r.riskIncluded=true;r.transitionLossIncluded=true;
   if(r.recoveryMoney<=x.moneyState.recoveryMoney||r.totalMargin>x.marginState.allowedMargin||r.grossExposure>=x.priorGrossExposure||r.netBigVolume>=x.priorBigGross||r.transitionLoss>x.transitionLossCap){r.details="LEVEL_GATES_FAILED";return r;}
   r.valid=true;r.status=HSBI_FS_EXACT_PROOF;r.reason=HSBI_REASON_OK;r.details="EXACT_LEVEL";return r;
}
HSBI_FutureSmallResult HSBI_SolveFutureSmall(const HSBI_FutureSmallInput &x)
{
   HSBI_FutureSmallResult r;ZeroMemory(r);r.status=HSBI_FS_REJECTED;r.reason=HSBI_REASON_INTERNAL_INVARIANT_FAILED;r.planId=x.planId;r.stateRevision=x.stateRevision;r.details="INVALID_INPUT";if(!HSBI_ValidateFutureSmallInput(x))return r;if(!HSBI_CalculateFutureSmallDepth(x.currentFar,x.volumeMin,x.conservativeQ,x.volumeStep,r.theoreticalDepth)){r.details="NONFINITE_DEPTH";return r;}
   double far=x.currentFar,priorBig=x.currentBigGross,priorExposure=x.currentGrossExposure;HSBI_MoneyStateSnapshot money=x.moneyState;HSBI_RiskSnapshot risk=x.riskState;HSBI_MarginSnapshot margin=x.marginState;bool terminal=false,boundConditions=true;
   for(int k=0;k<x.maximumDepth;k++)
   {
      HSBI_FutureSmallLevelInput li;ZeroMemory(li);li.levelIndex=k+1;li.farBefore=far;li.coreRatio=x.coreRatio;li.trendRatio=x.trendRatio;li.smallRatio=x.smallRatio;li.broker=x.broker;li.controlPrice=x.typedControlPrice;li.farCosts=x.farCosts;li.coreCosts=x.coreCosts;li.trendCosts=x.trendCosts;li.smallCosts=x.smallCosts;li.farOpenPrice=x.farOpenPrice;li.coreOpenPrice=x.coreOpenPrice;li.trendOpenPrice=x.trendOpenPrice;li.smallOpenPrice=x.smallOpenPrice;li.moneyState=money;li.riskState=risk;li.marginState=margin;li.minimumCompressionLots=x.minimumCompressionLots;li.minimumCompressionRatio=x.minimumCompressionRatio;li.maxNewFarRatio=x.maxNewFarRatio;li.transitionLossCap=x.transitionLossCap;li.executionSafetyBuffer=x.executionSafetyBuffer;li.priorBigGross=priorBig;li.priorGrossExposure=priorExposure;li.planId=x.planId;li.stateRevision=x.stateRevision;li.useInjectedBrokerProof=x.useInjectedBrokerProofs;li.testOnlyApproximation=x.testOnlyApproximation;if(x.useInjectedBrokerProofs)li.injectedBrokerProof=x.injectedBrokerProofs[k];
      HSBI_FutureSmallLevelResult level=HSBI_EvaluateFutureSmallLevel(li);if(!level.valid){r.details=level.details;return r;}HSBI_FutureSmallLevelProof proof;ZeroMemory(proof);proof.levelIndex=level.levelIndex;proof.farBefore=level.farBefore;proof.coreVolume=level.coreVolume;proof.trendVolume=level.trendVolume;proof.smallVolume=level.smallVolume;proof.netBigVolume=level.netBigVolume;proof.farAfter=level.farAfter;proof.compressionLots=level.compressionLots;proof.compressionRatio=level.compressionRatio;proof.recoverySlopeLots=level.recoverySlopeLots;proof.projectedRecoveryMoney=level.recoveryMoney;proof.projectedReserve=x.expectedReserve;proof.projectedMargin=level.totalMargin;proof.projectedRisk=level.riskValue;proof.transitionLoss=level.transitionLoss;proof.grossExposure=level.grossExposure;proof.moneyIncluded=level.moneyIncluded;proof.marginIncluded=level.marginIncluded;proof.riskIncluded=level.riskIncluded;proof.transitionLossIncluded=level.transitionLossIncluded;proof.proofStatus=HSBI_FS_EXACT_PROOF;proof.reason=HSBI_REASON_OK;r.levels[k]=proof;r.provenDepth=k+1;
      if(level.farAfter>x.conservativeQ*level.farBefore+HSBI_GridTolerance(x.volumeStep)||!level.moneyIncluded||!level.marginIncluded||!level.riskIncluded||!level.transitionLossIncluded)boundConditions=false;far=level.farAfter;priorBig=level.netBigVolume;priorExposure=level.grossExposure;money.recoveryMoney=level.recoveryMoney;risk.currentRisk=level.riskValue;margin.currentMargin=level.totalMargin;if(far<=x.volumeMin+HSBI_GridTolerance(x.volumeStep)){terminal=true;break;}
   }
   r.terminalFar=far;r.finiteSequence=terminal;bool bound=boundConditions&&HSBI_ValidateConservativeBound(x.currentFar,far,x.conservativeQ,r.provenDepth,x.roundingIncluded,x.costsIncluded,true,true,true);r.valid=r.provenDepth>=2&&(terminal||bound);r.status=terminal&&r.provenDepth>=2?HSBI_FS_EXACT_PROOF:(bound?HSBI_FS_CONSERVATIVE_BOUND:HSBI_FS_UNPROVEN);r.reason=r.valid?HSBI_REASON_OK:HSBI_REASON_INTERNAL_INVARIANT_FAILED;r.details=r.valid?(r.status==HSBI_FS_EXACT_PROOF?"EXACT_PROOF":"CONSERVATIVE_BOUND"):"UNPROVEN";r.proofDigest=HSBI_UlongToString(x.planId)+"|"+DoubleToString(r.terminalFar,8)+"|"+IntegerToString(r.provenDepth);return r;
}
#endif
