#ifndef ALE_DO_CORE_FLOW_COMMON_EXECUTIONCONTEXT_MQH_INCLUDED
#define ALE_DO_CORE_FLOW_COMMON_EXECUTIONCONTEXT_MQH_INCLUDED

struct ExecutionContext
  {
   long timestamp;
   int tick_index;
  };

#endif // ALE_DO_CORE_FLOW_COMMON_EXECUTIONCONTEXT_MQH_INCLUDED
