#ifndef ALE_DO_CORE_FLOW_COMMON_MARGINCONTEXT_MQH_INCLUDED
#define ALE_DO_CORE_FLOW_COMMON_MARGINCONTEXT_MQH_INCLUDED

struct MarginContext
  {
   double free_margin;
   double leverage;
  };

#endif // ALE_DO_CORE_FLOW_COMMON_MARGINCONTEXT_MQH_INCLUDED
