#ifndef ALE_DO_ERRORS_ERRORCODES_MQH_INCLUDED
#define ALE_DO_ERRORS_ERRORCODES_MQH_INCLUDED

enum ErrorCode
  {
   ERROR_NONE = 0,
   ERROR_UNKNOWN = 1
  };

#endif // ALE_DO_ERRORS_ERRORCODES_MQH_INCLUDED
