from pathlib import Path
text = (Path(__file__).resolve().parents[1] / "Include" / "StateMachine.mqh").read_text()
for state in [
    "STATE_BIG_HARVEST_CLOSE_BIG", "STATE_BIG_HARVEST_CLOSE_SMALL", "STATE_BIG_HARVEST_CALC_NET",
    "STATE_BIG_HARVEST_CLOSE_FAR", "STATE_BIG_HARVEST_CHECK_FINAL",
    "STATE_SMALL_CLOSE_SMALL", "STATE_SMALL_CLOSE_OLD_FAR", "STATE_SMALL_CLOSE_BIG_PART",
    "STATE_SMALL_BUILD_NEW_FAR", "STATE_SMALL_CHECK_RESERVE", "STATE_SMALL_OPEN_NEW_BIG", "STATE_SMALL_OPEN_NEW_SMALL",
]:
    assert state in text, state
assert "STATE_BIG_HARVEST_CLOSE_SMALL" in text and "STATE_BIG_HARVEST_CALC_NET" in text
assert "STATE_SMALL_CLOSE_OLD_FAR" in text and "STATE_SMALL_BUILD_NEW_FAR" in text
print("PENDING_FSM_PROGRESSION_CHECK PASS")
